/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alexc
 */
public class F1Frame extends javax.swing.JFrame {

    /**
     * Creates new form F1Frame
     */
    public F1Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        playersPanel = new javax.swing.JPanel();
        playersButton = new javax.swing.JButton();
        eventsPanel = new javax.swing.JPanel();
        eventsButton = new javax.swing.JButton();
        forecastPanel = new javax.swing.JPanel();
        forecastButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);

        playersPanel.setBackground(new java.awt.Color(13, 17, 59));
        playersPanel.setPreferredSize(new java.awt.Dimension(191, 450));

        playersButton.setBackground(new java.awt.Color(13, 17, 59));
        playersButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        playersButton.setForeground(new java.awt.Color(255, 255, 255));
        playersButton.setText("Players");
        playersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playersButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout playersPanelLayout = new javax.swing.GroupLayout(playersPanel);
        playersPanel.setLayout(playersPanelLayout);
        playersPanelLayout.setHorizontalGroup(
                playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(playersPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(playersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))
        );
        playersPanelLayout.setVerticalGroup(
                playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(playersPanelLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(playersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        eventsPanel.setBackground(new java.awt.Color(13, 59, 128));

        eventsButton.setBackground(new java.awt.Color(13, 59, 128));
        eventsButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        eventsButton.setForeground(new java.awt.Color(255, 255, 255));
        eventsButton.setText("Events");
        eventsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventsButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout eventsPanelLayout = new javax.swing.GroupLayout(eventsPanel);
        eventsPanel.setLayout(eventsPanelLayout);
        eventsPanelLayout.setHorizontalGroup(
                eventsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(eventsPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(eventsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))
        );
        eventsPanelLayout.setVerticalGroup(
                eventsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(eventsPanelLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(eventsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        forecastPanel.setBackground(new java.awt.Color(18, 9, 181));
        forecastPanel.setPreferredSize(new java.awt.Dimension(191, 450));

        forecastButton.setBackground(new java.awt.Color(18, 9, 181));
        forecastButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        forecastButton.setForeground(new java.awt.Color(255, 255, 255));
        forecastButton.setText("Forecast");
        forecastButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forecastButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout forecastPanelLayout = new javax.swing.GroupLayout(forecastPanel);
        forecastPanel.setLayout(forecastPanelLayout);
        forecastPanelLayout.setHorizontalGroup(
                forecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(forecastPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(forecastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))
        );
        forecastPanelLayout.setVerticalGroup(
                forecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(forecastPanelLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(forecastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(playersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eventsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(forecastPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(playersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eventsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(forecastPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void playersButtonMouseClicked(java.awt.event.MouseEvent evt) {
        playersFrame.run();
    }

    private void eventsButtonMouseClicked(java.awt.event.MouseEvent evt) {
        eventsFrame.run();
    }

    private void forecastButtonMouseClicked(java.awt.event.MouseEvent evt) {
        forecastFrame.run();
    }

    /*
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F1Frame().setVisible(true);
            }
        });
    } */

    public static void run() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F1Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton eventsButton;
    private javax.swing.JPanel eventsPanel;
    private javax.swing.JButton forecastButton;
    private javax.swing.JPanel forecastPanel;
    private javax.swing.JButton playersButton;
    private javax.swing.JPanel playersPanel;
    // End of variables declaration
}
